from abc import ABC, abstractmethod
class Robot(ABC):
    def __init__(self):
        self._model = None
        self._data = None
        self.state = {}
    @abstractmethod
    def reset_state(self):...
    @classmethod
    def create(self, xml_path):...
    @abstractmethod
    # def add_scalpel(self):...
    # @abstractmethod
    # def add_material(self): ...
    @abstractmethod
    def run_experiment(self): ...
    @property
    def model(self):...
    @property
    def data(self):...
        
            