from abc import ABC, abstractmethod

__all__ = ["Robot"]

class Robot(ABC):
    def __init__(self):
        self._model = None
        self._data = None
        self.state = {}

    @classmethod
    def create(self, xml_path): ...
    @abstractmethod
    def reset_state(self): ...
    @abstractmethod
    def set_shm_buffer(self): ...
    # @abstractmethod
    # def add_scalpel(self):...
    # @abstractmethod
    # def add_material(self): ...
    @abstractmethod
    def experiment_exeucte_wrapper(self, *args, **kwargs): ...
    @property
    def model(self): ...
    @property
    def data(self): ...
